### ISSUE TITLE
Issues with stats

### ISSUE THREAD

**Issue by emilbayes** [jasnell/notare#2]
![Screen Recording 2020-06-15 at 15 04 00](https://user-images.githubusercontent.com/416524/84661199-4a5f6e00-af1a-11ea-8679-2e180f543338.gif)

Hi! Trying out notare and a few "issues" and questions.
The above recording measures a script that runs some stuff on p2p system. It spawns a child process, open an TCP IPC connection, makes a few http requests and sets some timers. Memory usages looks correct.

1. Is event loop latency in nanoseconds? Some tools measure latency as a percentage of execution time, do you know how this is calculated?
2. CPU usage seems off. Activity monitor never measures more than 10%, so wondering if it's affected by an outlier like a huge spike?
3. Handles is always empty. Should it have picked up the TCP handles, timers and such here?
4. Is there an easy way to get GC metrics also (old / new, GC pauses)? Happy to do a PR

**Comment by emilbayes** [comment]
Uploaded here as video also: https://i.imgur.com/0uN6jlm.mp4

**Comment by emilbayes** [comment]
Sorry 3. I realised I hadn't set `NOTARE_HANDLES`. I should have read the docs 😅

**Comment by jasnell** [comment]
1. Event loop latency is absolutely in nanoseconds. Notare is graphing the percentiles of the event loop detail histogram. https://nodejs.org/dist/latest-v14.x/docs/api/perf_hooks.html#perf_hooks_perf_hooks_monitoreventloopdelay_options

2. CPU calculation is definitely off. I'm thinking of pulling this one anyway, to be honest, as it is extremely difficult to get correct and is rarely useful enough to be worth the effort of making it correct. Once the support for it lands in libuv, I want to replace the CPU utilization with an event loop utilization metric that is significantly more useful.

3. As you found, handles is off by default because enabling the async hook to monitor them is extremely expensive to have on by default.

4. We absolutely could add GC metrics.
